name: countries_and_flags
description: "search and add your favorite countries to your collection"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  dio: ^5.8.0+1
  reactive_forms: ^17.0.1
  collection: ^1.19.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_riverpod_logger: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
